services:
  # Base de datos (Cerrada al mundo exterior)
  db:
    image: postgres:15-alpine
    container_name: bucle-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER} # üëá Usamos variables
      POSTGRES_PASSWORD: ${DB_PASS} # üëá Usamos variables
      POSTGRES_DB: circular_db
    # ‚ùå BORRAMOS LA SECCI√ìN PORTS (Nadie entra desde fuera)
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Backend
  backend:
    build: ./CircularApp-Backend
    container_name: bucle-backend
    ports:
      - "7860:7860"
    volumes:
      - ./CircularApp-Backend/uploads:/app/uploads
    depends_on:
      - db
    environment:
      # Conectamos usando las variables secretas
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASS}@db:5432/circular_db
      SECRET_KEY: ${SECRET_KEY}
    restart: always

  # Frontend
  frontend:
    build: ./CircularApp-Frontend
    container_name: bucle-frontend
    ports:
      - "3000:3000"
    environment:
      # üëá AQU√ç ES DONDE PONDR√ÅS LA IP DE HUAWEI LUEGO
      NEXT_PUBLIC_API_URL: ${API_URL}
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data:
