services:
  backend:
    build: ./CircularApp-Backend
    container_name: bucle-backend
    environment:
      - DATABASE_URL=sqlite:///./sql_app.db
    ports:
      - "7860:7860"
    volumes:
      - ./CircularApp-Backend/sql_app.db:/app/sql_app.db
      - ./CircularApp-Backend/uploads:/app/uploads
    restart: always

  frontend:
    build: ./CircularApp-Frontend
    container_name: bucle-frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:7860"
    depends_on:
      - backend
    restart: always
