services:
  # Base de datos (Cerrada al mundo exterior)
  db:
    image: postgres:15-alpine
    container_name: bucle-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: circular_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./CircularApp-Backend
    container_name: bucle-backend
    ports:
      - "7860:7860"
    volumes:
      - ./CircularApp-Backend/uploads:/app/uploads
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASS}@db:5432/circular_db
      SECRET_KEY: ${SECRET_KEY}
    restart: always

  frontend:
    build: ./CircularApp-Frontend
    container_name: bucle-frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: "176.52.137.246"
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data:
