services:
  db:
    image: postgres:15-alpine
    container_name: bucle-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Valentin_03
      POSTGRES_DB: circular_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./CircularApp-Backend
    container_name: bucle-backend
    ports:
      - "7860:7860"
    volumes:
      - ./CircularApp-Backend/uploads:/app/uploads
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:Valentin_03@db:5432/circular_db
    restart: always

  frontend:
    build: ./CircularApp-Frontend
    container_name: bucle-frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:7860"
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data:
